ARG NODE_VERSION=16
ARG SERVER_PORT=3000

FROM node:$NODE_VERSION-buster as base 

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn lerna bootstrap
RUN rm -rf /app/packages/client/dist/ && yarn build --scope=client
RUN rm -rf /app/packages/server/dist/ && yarn build --scope=server

EXPOSE ${SERVER_PORT}
CMD [ "node", "/app/packages/server/dist/index.js" ]